### PR TITLE
fix holes only on corners

### LINKED ISSUE #88: "Only cut magnet/screw holes at corners" doesn't work
It seems to just suppress the holes entirely. (OpenSCAD 2023.03.17 snapshot.) I love the idea though...

### PR DESCRIPTION
**Pull request by Ruudjhuu**
Fixes  #88

### CODE REVIEW

**Comment by spuder** [comment]
Thank you for fixing this. I was wondering why the holes were working a few commits ago, but suddenly seemed to stop working.

**Comment by spuder** [comment]
It seems the 'only corners' feature isn't working. Tested on commit 1b9f71b4b541eb1676a17e6be94d365dd7aacb38

Screen Shot 2023-03-21 at 8 31 43 PM

**Comment by Ruudjhuu** [comment]
Thanks for pointing out that this is not yet working for you. 

Could you provide some more information about how to reproduce? I am not able to mimic your outcome.

The steps I took:
1. `git clone https://github.com/Ruudjhuu/gridfinity-rebuilt-openscad.git`
2. `checkout hotfix/holes_at_corners`
3. change in `gridfinity-rebuilt-bins.scad` -> `gridx = 4` `gridy = 1`
4. `openscad gridfnity-rebuiltj-bins.scad`
5. In the UI, check `only corners`
6. repeat step 3-6 for `gridx = 1` `gridy = 4`

image

**Comment by spuder** [comment]
There must have been something wrong with my test. Please disregard my previous comment.

**Comment by mastersta** [comment]
Tested and working, thanks for fixing it.

**Comment by DJDDDM** [comment]
seems fine. make sure to run your regression tests, as these exist exactly for cases like these.
approved.

**Review by DJDDDM — COMMENTED** [review]
code seems fine and test done by https://github.com/kennetek/gridfinity-rebuilt-openscad/pull/89#issuecomment-1509102570

**Review by DJDDDM — APPROVED** [review]
code seems fine and test done by https://github.com/kennetek/gridfinity-rebuilt-openscad/pull/89#issuecomment-1509102570

**Pull request merged**
