### PR TITLE
Remove trailing whitespace, add pre-commit and CI workflow to check whitespace

### PR DESCRIPTION
**Pull request by smkent**
This model is so useful! I've been printing a lot of Gridfinity bins and am starting to customize my own. That's led me to dig through the OpenSCAD code to make customizations.

To make development easier, this PR:

* Adds whitespace fixes -- removes trailing whitespace and adds newlines at the end of all files
* Adds [pre-commit](https://pre-commit.com/) to fix these issues at commit time
  * A developer can enable these hooks with `pre-commit install` within their cloned repository
* Adds a GitHub Actions workflow to run pre-commit's whitespace checks on PRs, so all new code will be consistent

### CODE REVIEW

**Comment by smkent** [comment]
See [this test PR in my fork](https://github.com/smkent/gridfinity-rebuilt-openscad/pull/1) and [workflow run](https://github.com/smkent/gridfinity-rebuilt-openscad/actions/runs/6270781632/job/17029257349) for an example of the GitHub Action being added.

**Comment by smkent** [comment]
Hi, is there interest in merging this PR? Thanks!

**Review by Ruudjhuu — APPROVED** [review]

**Comment by Ruudjhuu** [comment]
Is there a way to show more information for the CI run? like files and line numbers?

**Comment by smkent** [comment]
> Is there a way to show more information for the CI run? like line numbers?

Yep! Updated. Check it out: https://github.com/kennetek/gridfinity-rebuilt-openscad/actions/runs/7432741288/job/20224893804?pr=128

**Comment by smkent** [comment]
🎉

**Pull request merged**
