### PR TITLE
Gridfinity Lite support (closes #14)

### LINKED ISSUE #14: Gridfinity lite
I'm not sure if you've noticed [this discussion](https://www.reddit.com/r/gridfinity/comments/x8itxd/i_created_some_hacked_plain_gridfinity_storage/) around [this fork](https://github.com/JakeWorrell/gridfinity-rebuilt-openscad) that has some outputs out on [Printables](https://www.printables.com/model/265271-gridfinity-lite-economical-plain-storage-bins), but I thought the idea of having an option to do "lite" bins was great and was wondering if you were planning to add something like this.

### PR DESCRIPTION
**Pull request by rcarmo**
This pull request adds the changes @JakeWorrel did to create a "lite" version of the bins that uses much less filament (and prints significantly faster for me), as well as a small Python script that generates sets of bins (@JakeWorrel had a PHP version, but I use Python for everything...).

### CODE REVIEW

**Comment by Ruudjhuu** [comment]
I like the Idea.

However, I am not fan of the python script. 
* I only see a use case for this script if @kennetek wants to upload this work on any 3d print sharing site. It does not have anything to do with the lite support.
* The python implementation only suports unix like operating systems. So it is useless for Windows users. The rest of this repo is also usable with Windows
* The script only targets lite bins. No other features.
*  The use of `system()` is not recommended, use `subprocess`. You can't handle any output / errors with `system()`
*  When a file exists, it does nothing. If you want to regenerate everything you need to manually remove everything. Behavior depends on the users filesystem.

**Comment by rcarmo** [comment]
Well, I can remove it. It was just a quick port anyway, and since I'm on the Linux side of the Universe (yes, really) I didn't think it was an issue.

**Comment by rcarmo** [comment]
Done.

**Comment by kennetek** [comment]
Sorry, I have not had a chance to look at this at all. I'm extremely busy, but I plan on proofreading and making any necessary changes to the code one of these weekends, as this is one of the most requested features. 

I've never used Python with OpenSCAD, so I don't really have an opinion on including a script or not. I'd have to look into it. Sorry for the delays

**Comment by JakeWorrell** [comment]
Hey gang, I'm the guy who did the 'lite' hacks and I just wanted to say I'm more than happy for you to go ahead with this. I didn't do a PR myself as I wasn't sure that my scad code was up to the same quality as @kennetek's - to be honest I was quite surprised to see this here!

**Comment by rcarmo** [comment]
It works fine. The only change I made was reverting the little offset change, because I found that (in my printer) that wasn’t necessary and left a slight outline.

**Comment by kennetek** [comment]
I promise I started with what @JakeWorrell made, but there were a couple things that I felt needed to be implemented for it to be a proper new feature. For one, what if magnets were still desired. This might be a bit of a weird case, but it was easy enough to implement. Additionally, and more importantly, what if the divider lines did not line up with the grid (for instance, 3x3 grid split in half). Since the baseplates required me to implement scaling of the bases, it was easy to use a negative scaling. This means the original lite module was made unnecessary, sadly. Because generating these bases requires information about the cutters, and some variables (scoop, internal height) are mutually exclusive with lite, I moved it to a new file for clarity. Let me know what you all think. 

Example pushing it to its limits:
image

**Comment by rcarmo** [comment]
As long as it works and we have one reference repo with all the features, I’m all for it. :)On 6 Nov 2022, at 06:35, Kenneth ***@***.***> wrote:﻿
I promise I started with what @JakeWorrell made, but there were a couple things that I felt needed to be implemented for it to be a proper new feature. For one, what if magnets were still desired. This might be a bit of a weird case, but it was easy enough to implement. Additionally, and more importantly, what if the divider lines did not line up with the grid (for instance, 3x3 grid split in half). Since the baseplates required me to implement scaling of the bases, it was easy to use a negative scaling. This means the original lite module was made unnecessary, sadly. Because generating these bases requires information about the cutters, and some variables (scoop, internal height) are mutually exclusive with lite, I moved it to a new file for clarity. Let me know what you all think.
Example pushing it to its limits:

**Comment by JakeWorrell** [comment]
Great work @kennetek, looks much more thorough than my approach. I will have a play as soon as I get chance

**Pull request merged**
