### PR TITLE
Added chamfer option for bottom screwholes

### PR DESCRIPTION
**Pull request by Le0Michine**
Chamfer prints slightly nicer than a slit and works just as well, so I added it as an option

### CODE REVIEW

**Comment by Le0Michine** [comment]
Screenshot 2022-12-11 181222

**Comment by kennetek** [comment]
What is the use case for this feature? I understand it makes the geometry easier to print, but doesn't it make the screw hole not work anymore?

**Comment by Le0Michine** [comment]
I think it still should work, there is almost 1mm of thickness left which is plenty for strong enough connection. Assuming one puts screws from the top. If you are screwing from the baseplate side than it could be an issue

Thinking more about this should there be a separation of magnet base and screw base since you can't use both at the same time

**Comment by kennetek** [comment]
I'm sorry, but I can't add this in. I feel like it compromises both the screw and magnet usability, given how the screw will have barely any engagement, and the magnet will have no solid backing, likely causing it to recess into the part and lose strength. This would maybe be acceptable for the sake of printability, however style 3 is already a really effective way to print this geometry without sacrificing screw or magnet effectiveness.

**Pull request closed without merging**
