### PR TITLE
Add option to offset to one side when fitting to drawer

### PR DESCRIPTION
**Pull request by nelsongraca**
I love the option to be able to fit to a drawer, however I have a specific case where I would like to have the excess material only on the back side of the drawer instead of evenly spaced.

For that I added 2 new parameters that allow to control just that called `fitx` and `fity`  when -1 the fill will be only to the left (x) or bottom (y), 0 is the same behavior as before so it splits equally, and when 1 will be only to the right or up.

### CODE REVIEW

**Comment by Ruudjhuu** [comment]
Is this a duplicate of #49

**Comment by nelsongraca** [comment]
> Is this a duplicate of #49?

True I missed it, but these changes while less flexible add less complexity.

**Comment by Paradigm999** [comment]
If distancex or distancey equal 0 and fitx or fity are not 0 the resulting model comes out odd.
I added a check on lines 79 and 80 to resolve this:
```
offsetx = dix == 0 ? 0 : (gx*length-0.5-dix)/2*fitx*-1;
offsety = diy == 0 ? 0 : (gy*length-0.5-diy)/2*fity*-1;
```

Line 43 should probably also have a vanilla default value of 0"
`fitx = 0; // [-1:1]`

**Comment by Paradigm999** [comment]
After some more testing this works better for lines 79 and 80:
```
offsetx = dix < dx ? 0 : (gx*length-0.5-dix)/2*fitx*-1;
offsety = diy < dy ? 0 : (gy*length-0.5-diy)/2*fity*-1;
```

**Review by kennetek — CHANGES_REQUESTED** [review]
I like this feature. I think this is a better implementation than #49. It makes sense that the overall length is defined in each direction (the inside of a drawer, the space available on a desk) and then define the orientation in both axes. What is also nice is that the value isn't actually -1 or 1, it can be anything in-between. It is effectively a weight for which side gets the extra space. @Paradigm999 is right however, there needs to be a safety check for if there isn't any extra space available, as well as have a default of zero. Their code seems to do a good job of fixing the issue.

**Comment by nelsongraca** [comment]
@kennetek and @Paradigm999 thank you for your comments, I will implement the changes, improve doc and push them ASAP.

**Comment by nelsongraca** [comment]
@kennetek Changes done please review

**Review by kennetek — APPROVED** [review]

**Comment by kennetek** [comment]
Perfect!

**Pull request merged**
